parameter_defaults:
  # only for in-LAB ussage:
  # echo "192.168.0.79    overcloud.example.com overcloud" >> /var/lib/libvirt/dnsmasq/OSP-d_Provisioning.addnhosts
  # and kill -HUP <PID of right dnsmasq process>
  # to make this work without a full blown bind
  #DnsServers: ["172.30.10.4"]

  # The DNS domain used for the hosts. This must match the overcloud_domain_name configured on the undercloud.
  # Type: string
  CloudDomain: bxlab.lunetix.org

  # The DNS name of this cloud. E.g. ci-overcloud.tripleo.org
  # Type: string
  CloudName: overcloud.bxlab.lunetix.org

  # The DNS name of this cloud's provisioning network endpoint. E.g. 'ci-overcloud.ctlplane.tripleo.org'.
  # Type: string
  CloudNameCtlplane: overcloud.ctlplane.bxlab.lunetix.org

  # The DNS name of this cloud's internal API endpoint. E.g. 'ci-overcloud.internalapi.tripleo.org'.
  # Type: string
  CloudNameInternal: overcloud.internalapi.bxlab.lunetix.org

  # The DNS name of this cloud's storage endpoint. E.g. 'ci-overcloud.storage.tripleo.org'.
  # Type: string
  CloudNameStorage: overcloud.storage.bxlab.lunetix.org

  # The DNS name of this cloud's storage management endpoint. E.g. 'ci-overcloud.storagemgmt.tripleo.org'.
  # Type: string
  CloudNameStorageManagement: overcloud.storagemgmt.bxlab.lunetix.org

